//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsycoTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultScore
    {
        public int ResultScoreId { get; set; }
        public int ResultScoreTestId { get; set; }
        public string ResultScoreName { get; set; }
        public int ResultScoreValue { get; set; }
    
        public virtual Test Test { get; set; }
    }
}
