//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PsycoTest.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeAnswer
    {
        public int TakeResultId { get; set; }
        public int TakeAnswerId { get; set; }
        public Nullable<int> TakeScore { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Result Result { get; set; }
    }
}
